config/routes.rb
Ey::Application.routes.draw do
  
  get "static_pages/home"
  get "static_pages/help"

  get '/signout', to: 'sessions#destroy'

  get '/auth/:provider/callback' => 'users#login'
  root to: 'static_pages#home'

  resources :users do
    collection do
      get :friends, :page_friends, :autocomplete_location_address, :page_search_criteria, :like_list, :page_like_list
    end
    member do
      patch :add_location, :badges, :add_testimonial, :add_picture
      get :search_criteria, :likes, :pics_edit, :set_default_pic, :set_visible_pic, :likes_testimonial, :delete_testimonial
      post :update_status, :update_about_me
    end
  end

  

end

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.2.0/respond.min.js"></script>
     <![endif]-->

app/views/layouts/_sidebar.html.erb
        <!-- START Template Sidebar (Left) -->
        <aside class="sidebar sidebar-left sidebar-menu">
            <!-- START Sidebar Content -->
            <section class="content slimscroll">
                <h5 class="heading">Main Menu</h5>
                <!-- START Template Navigation/Menu -->
                <ul class="topmenu topmenu-responsive" data-toggle="menu">
                    <li >
                        <a href="#">
                            <span class="figure"><i class="ico-home2"></i></span>
                            <span class="text">Home</span>
                        </a>
                    </li>
                    <li class="active">
                        <a href="/">
                            <span class="figure"><i class="ico-user2"></i></span>
                            <span class="text">Profile</span>
                        </a>
                    </li>
                    <li>
                        <a href="<%=  friends_users_path %>">
                            <span class="figure"><i class="ico-users2"></i></span>
                            <span class="text">Facebook Friends</span>
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <span class="figure"><i class=" ico-menu6"></i></span>
                            <span class="text">Timeline</span>
                        </a>
                    </li>
                    <li>
                        <a href="<%=  like_list_users_path %>">
                            <span class="figure"><i class=" ico-star6"></i></span>
                            <span class="text">Like list</span>
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <span class="figure"><i class="ico-heart"></i></span>
                            <span class="text">Crush list</span>
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <span class="figure"><i class="ico-bell"></i></span>
                            <span class="text">Notifications</span>
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <span class="figure"><i class="ico-user-minus"></i></span>
                            <span class="text">Hidden people</span>
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <span class="figure"><i class="ico-envelope-alt"></i></span>
                            <span class="text">Messages</span>
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <span class="figure"><i class=" ico-user-block"></i></span>
                            <span class="text">Blocked people</span>
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            <span class="figure"><i class=" ico-blog2"></i></span>
                            <span class="text">Discussions / Blogs</span>
                        </a>
                    </li>
                </ul>
                <!--/ END Template Navigation/Menu -->

                <!--/ END Sidebar summary -->
            </section>
            <!--/ END Sidebar Container -->
        </aside>
        <!--/ END Template Sidebar (Left) -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="Express yourself landing page.">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %> 
</head>
<body>

<% if signed_in? %>
            
                  <!-- top nav -->
                    <%= render 'layouts/header' %>
                  <!-- /top nav -->
            
                  <!-- sidebar -->
                    <%= render 'layouts/sidebar' %>
                  <!-- /sidebar -->
                
                  
                
                          <!-- START Template Main -->
                            <section id="main" role="main">
                                <!-- START Template Container -->
                                <div id="main_container" class="container-fluid">
                                    <%= yield %>                                    
                                </div>
                                <!--/ END Template Container -->

                                <!-- START To Top Scroller -->
                                <a href="#" class="totop animation" data-toggle="waypoints totop" data-showanim="bounceIn" data-hideanim="bounceOut" data-offset="50%"><i class="ico-angle-up"></i></a>
                                <!--/ END To Top Scroller -->

                            </section>
                          <!--/ END Template Main -->
<div id="fb-root"></div>
              <div id="status"></div>
            
 

<% else %>
  <%= yield %>
<% end %>


</body>
</html>
<script>

  //Turbolinks.enableTransitionCache();

    $('#fb_login').click(function(){
        checkLoginState();
    });
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
    //  testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
 //     document.getElementById('status').innerHTML = 'Please log ' +
   //     'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
    //  document.getElementById('status').innerHTML = 'Please log ' +
      //  'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
        return FB.login(function(response) {
          if (response.authResponse) {
            return window.location = '/auth/facebook/';
          }
        });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '<%= FACEBOOK_CONFIG["FACEBOOK_APP_ID"] %>',
    status     : true,  // check login status
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.1
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

    return $('#fb_signout').click(function(e) {
    FB.getLoginStatus(function(response) {
      if (response.status === 'connected') {
        // the user is logged in and has authenticated your
        // app, and response.authResponse supplies
        // the user's ID, a valid access token, a signed
        // request, and the time the access token 
        // and signed request each expire
        var uid = response.authResponse.userID;
        var accessToken = response.authResponse.accessToken;
      } else if (response.status === 'not_authorized') {
        // the user is logged in to Facebook, 
        // but has not authenticated your app
      } else {
        // the user isn't logged in to Facebook.
      }
        return FB.logout(); 
   });
    return true;
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }

       $('body').on('click', '.images_div', function(){
        $(".profile_pics").magnificPopup({
              type: "image",
              gallery: {
                  enabled: true
              }
          }).magnificPopup('open');

       
        
      });


</script>